name: Close milestone
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Needs to match, exactly, the name of a milestone
  workflow_call:
    inputs:
      version_call:
        description: Needs to match, exactly, the name of a milestone
        required: true
        type: string

jobs:
  main:
    if: github.repository == 'grafana/grafana'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: main
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: "Generate token"
        id: generate_token
        uses: tibdex/github-app-token@0914d50df753bbc42180d982a6550f195390069f
        with:
          app_id: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_ID }}
          private_key: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_PEM }}
      - name: Close milestone (manually invoked)
        if: ${{ github.event.inputs.version != '' }}
        uses: ./actions/close-milestone
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - name: Close milestone (workflow invoked)
        if: ${{ inputs.version_call != '' }}
        uses: ./actions/close-milestone
        with:
          version_call: ${{ inputs.version_call }}
          token: ${{ steps.generate_token.outputs.token }}
